### ISSUE TITLE
Proper logging

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#10]
We should use proper logging like winston, so we would get our logs being dumped to i.e. text file, or db in case of server issues.

**Comment by Jordan141** [comment]
## Logging required:
### Warning/Error logging:
All warning and errors should be logged with:
- issue
- stacktrace
- date and time of occurrence
- article, user or comment details if applicable.

### Activity logging
User activity should be logged anonymously to improve app performance, security and to determine most liked features and articles. What we log of said information can be discussed in this ticket.
- User actions
- Time spent on webpage
