### ISSUE TITLE
No "Approve" button in unapproved articles for admin

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#132]
After navigating to an unapproved article from moderation panel, there's no "approve" button under the article's content.

**Comment by michaelKurowski** [comment]
![image](https://user-images.githubusercontent.com/2772942/103134833-5dff4480-46b4-11eb-9b7f-3b37cecf92ec.png)

**Comment by michaelKurowski** [comment]
Might require approval logic if there's none.

**Comment by Jordan141** [comment]
Thanks, meant to fix this, the actual bug is the url you're being directed to. It's the show route, not approve route, if you go to article/approve/id instead of article/id as per that, you'll have the approve button. I'll fix it soon.
