### ISSUE TITLE
Header styling issues

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#139]
Header looks poorly on mobile chrome

![Screenshot_2020-12-25-18-25-01-997_com android chrome](https://user-images.githubusercontent.com/2772942/103138782-974caa00-46de-11eb-9c6d-8f92658f2e70.jpg)

**Comment by Jordan141** [comment]
Top stories article header looks a bit funky too, might be worth adding some fixes for that in here too
