### ISSUE TITLE
Serve Images in Next-Gen Formats

### ISSUE THREAD

**Issue by Jordan141** [Jordan141/articleblog#151]
Image formats like JPEG 2000, JPEG XR, and WebP often provide better compression than PNG or JPEG, which means faster downloads and less data consumption

**Comment by Jordan141** [comment]
Efficiently encode images also
https://web.dev/uses-optimized-images/?utm_source=lighthouse&utm_medium=devtools

**Comment by michaelKurowski** [comment]
https://github.com/imgproxy/imgproxy suggested by Matt

**Comment by Jordan141** [comment]
Done as of #321
