### ISSUE TITLE
Categories should be a multiselect

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#163]
![image](https://user-images.githubusercontent.com/2772942/103153097-3aa8c800-478e-11eb-9fb8-b6005a2cd121.png)

One article should be assignable to multiple categories.
I.e. article about v8, is also an article about JS.

**Comment by michaelKurowski** [comment]
pro-tip:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select#Advanced_select_with_multiple_features

**Comment by Jordan141** [comment]
I'll tackle this after #19 and #63

**Comment by Jordan141** [comment]
Blocked by current PRs
