### ISSUE TITLE
Moderation panel crashing when no articles to approve

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#172]
Modertion panel crashes when there's no article to approve.
![image](https://user-images.githubusercontent.com/2772942/103154494-e1459680-4797-11eb-8994-3599068c4306.png)

**Comment by michaelKurowski** [comment]
Actually moderation panel doesn't work at all, the error always throws

**Comment by Jordan141** [comment]
Must be a side effect of the global change from earlier
