### ISSUE TITLE
Sanitize data

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#184]
We need to sanitize data, especially the one coming from login/register and comments

**Comment by Jordan141** [comment]
Some reading material on the subject
[Link 1](http://shebang.mintern.net/foolproof-html-escaping-in-javascript/)
[Link 2](https://cheatsheetseries.owasp.org/cheatsheets/Cross_Site_Scripting_Prevention_Cheat_Sheet.html#RULE_.233_-_JavaScript_Escape_Before_Inserting_Untrusted_Data_into_HTML_JavaScript_Data_Values)
[Link 3](https://owasp.org/www-community/Injection_Theory)

**Comment by Jordan141** [comment]
Fixed in #253
