### ISSUE TITLE
Auto-deploy broke

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#217]

**Comment by michaelKurowski** [comment]
Website no longer auto deploys

**Comment by michaelKurowski** [comment]
Last commit on server

```
commit 2170ee1753b25fb527329ed1dec14a8230235cb8 (HEAD, origin/master, origin/HEAD)
Author: Jordan Moss <jmoss636@gmail.com>
Date:   Thu Dec 31 01:52:46 2020 +0000

    fullname should be shorter
```

**Comment by michaelKurowski** [comment]
Found likely reason, the CI fails at activating the webhook.
Webhook might not be working.
![image](https://user-images.githubusercontent.com/2772942/103706314-ec28d400-4fac-11eb-8912-d3b46f0fd342.png)

**Comment by michaelKurowski** [comment]
Webhooks were down on the server.
I've set them up and re-ran CI job on the last commit. Works:
![image](https://user-images.githubusercontent.com/2772942/103706635-6c4f3980-4fad-11eb-9a2a-a1db850c73d0.png)

**Comment by michaelKurowski** [comment]
@Jordan141 FYI in the future if autodeploy won't work, check whether CIs on latest commits are failing, and if you see connection fails, then go to server and run script  `<repository directory>/devops/start.sh`.

It may happen tho, that you'll also have to set permissions of ./db directory to something permissive, like `sudo chmod 777 -R ./db`, if the webhook generates log about permissions in `devops/redeploy.log`, after CI finishes.

**Comment by michaelKurowski** [comment]
The issue still persists after doing the above. I'll check it later on.

**Comment by Jordan141** [comment]
Seems to be resolved, removing from milestone.
