### ISSUE TITLE
Hot Reloading

### ISSUE THREAD

**Issue by Jordan141** [Jordan141/articleblog#23]
Enable Hot Reloading for code while it's in the docker instance

**Comment by michaelKurowski** [comment]
You need to add entry for all files containing editable content into docker-compose's volume mappings. 

In addition to that, you don't seem to use web pack, but nodemon should have an option for reloading connected with files watching. 

If the server reads file every time and compiles that, you don't need a watcher. 

In dev mode however I'd expect that pages would be precompiled. 
That is when you push changes to master, CI should auto deploy compiled pages to a server.

**Comment by Jordan141** [comment]
Solved in #27
