### ISSUE TITLE
Allow more characters for content and title

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#283]
"yes, a whitelist is more secure than a denylist, but in this case using a denylist really hurts UX; what if I want to write an article about the <picture> tag? I would like to title it "Responsive images using <picture> tag"
Matt presented a valid point. I think that the approach we use seems rather ancient from UX point of view. We basically have to allow a lot of character combinations while still keeping it secure.

**Comment by Jordan141** [comment]
@michaelKurowski this was solved in the above PR, but the articulation makes me believe you also want a higher character limit for article content and title. If this isn't true, feel free to close this.

**Comment by michaelKurowski** [comment]
It's about allowing all kinds of characters in title and content. If it's already done you can close it @Jordan141
