### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#291]
Delete account button is a dummy rn, we need to make it work.

**Comment by michaelKurowski** [comment]
@Jordan141 do we have the backend implementation

**Comment by Jordan141** [comment]
> @Jordan141 do we have the backend implementation

Not for deleting users, just articles. Which is a DELETE request to the article route

**Comment by michaelKurowski** [comment]
We'll need one for users then I guess

**Comment by michaelKurowski** [comment]
Or maybe it should display info to email us?
