### ISSUE TITLE
Plan layout implementation

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#31]
Desktop:
 - homepage / articles listing
 - categories listing
 - authors
 - profile
 - edit profile
 - add/edit article
- register
- login
- article

Mobile:
 - homepage / articles listing
 - categories listing
 - authors
 - profile
 - edit profile
- register
- login
- article

Create tickets for layout implementation

**Comment by michaelKurowski** [comment]
https://www.digitalocean.com/community/tutorials/how-to-use-ejs-to-template-your-node-application

**Comment by michaelKurowski** [comment]
https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by Jordan141** [comment]
blocked by #30

**Comment by michaelKurowski** [comment]
Unblocked, designs done. But this task has to be splitted into subtasks.

**Comment by michaelKurowski** [comment]
Tickets created
