### ISSUE TITLE
Fix layout for Safari

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/articleblog#80]
Fix layout after migration to EJS

**Comment by michaelKurowski** [comment]
I have to wait till layout problems on FF and chrome will be fixed

**Comment by MarcinGrzeszczak** [comment]
Iphone XR
IOS 14.3
Safari 14.3

![574526A7-A83A-42C0-9C3D-0E00915D8F4F](https://user-images.githubusercontent.com/10917792/103153347-3b425e00-4790-11eb-8306-67f493557c59.png)
![B681E43F-97B5-4657-96C0-AFC15240C4A7](https://user-images.githubusercontent.com/10917792/103153352-41d0d580-4790-11eb-973c-48f4f667d571.png)
![5B28A042-C506-4E81-950C-E46DBE464AD4](https://user-images.githubusercontent.com/10917792/103153353-44332f80-4790-11eb-98c0-e3bbfd871755.png)
![560ABCF8-106C-4CF9-89BC-C9E62E2874FB](https://user-images.githubusercontent.com/10917792/103153354-45fcf300-4790-11eb-915b-249a44909228.png)
![C046AF1B-D34F-4326-86A5-7722643DF3E7](https://user-images.githubusercontent.com/10917792/103153358-49907a00-4790-11eb-805d-a2c63c99cb9c.png)
![20391750-7CB6-4E84-BB25-FB986A8E4698](https://user-images.githubusercontent.com/10917792/103153359-4a291080-4790-11eb-90b4-1074dc22ae57.png)
![7CB62D9C-5EFA-4AC4-AC97-98224285A2A4](https://user-images.githubusercontent.com/10917792/103153362-4bf2d400-4790-11eb-9217-60819147e766.png)
![04527D71-B817-4B77-98AA-685BC373D83D](https://user-images.githubusercontent.com/10917792/103153363-4d240100-4790-11eb-95c7-cdd62ef0d6d3.png)
![51496ACC-A170-4EDD-AD09-FC3B7783D5A6](https://user-images.githubusercontent.com/10917792/103153364-4e552e00-4790-11eb-9f21-36a1c1a2f2fe.png)
![6ABC6EB0-603E-4B53-AEC7-D893EC81879F](https://user-images.githubusercontent.com/10917792/103153366-4f865b00-4790-11eb-9ef7-51b50f2885c8.png)
![ECE7BB07-0ABC-47CC-B1BF-ACD3C3E8EBA6](https://user-images.githubusercontent.com/10917792/103153367-51501e80-4790-11eb-9003-a875431cd7cf.png)
![86EC53D4-5F7E-4301-9FA7-9D28ADED2A86](https://user-images.githubusercontent.com/10917792/103153369-51e8b500-4790-11eb-88b3-5d684e685bb5.png)
![9890F20C-B69D-45EB-8C73-5F45CF530A56](https://user-images.githubusercontent.com/10917792/103153370-5319e200-4790-11eb-9a2a-596fc06fd577.png)
![B4541665-FA37-4CFA-919E-28DE8D34CBA3](https://user-images.githubusercontent.com/10917792/103153371-54e3a580-4790-11eb-9f31-762841bc2472.png)
![7071C3D1-6D4D-42DF-9E1B-3478086B2571](https://user-images.githubusercontent.com/10917792/103153448-d76c6500-4790-11eb-9ad9-4ca7c1eb9f70.png)
![6B253296-95F2-43F8-8F85-5868FA23AF57](https://user-images.githubusercontent.com/10917792/103153456-de937300-4790-11eb-8334-23a4ce4f9202.png)
![ECF16411-2734-4AD5-A294-F83F187E87A5](https://user-images.githubusercontent.com/10917792/103153457-df2c0980-4790-11eb-80f0-c8bc1717ef93.png)
![CC126021-6A1F-4A72-BD74-298808046FA7](https://user-images.githubusercontent.com/10917792/103153458-e0f5cd00-4790-11eb-89b2-3ff8778119f7.png)
![A73DC8FD-A2A9-4AB9-A6DD-7CFAF71A3B8D](https://user-images.githubusercontent.com/10917792/103153459-e2bf9080-4790-11eb-82a4-ccebf7a19a74.png)

**Comment by michaelKurowski** [comment]
I see only one problem - some pages are wider than the header. Let me know if I don't notice sth

**Comment by MarcinGrzeszczak** [comment]
MacBook Air 13 early 2015
macOS Big Sur 11.0.1
Safari 14.0.1
Resolution: 2560x1080
External Monitor
![Zrzut ekranu 2020-12-26 o 16 01 19](https://user-images.githubusercontent.com/10917792/103153932-a4c46b80-4794-11eb-89d0-2163083df5e9.png)
![Zrzut ekranu 2020-12-26 o 16 01 32](https://user-images.githubusercontent.com/10917792/103153934-a8f08900-4794-11eb-8e54-e909f4a43681.png)
![Zrzut ekranu 2020-12-26 o 16 01 48](https://user-images.githubusercontent.com/10917792/103153936-aee66a00-4794-11eb-81e2-d0d198d5d6bd.png)
![Zrzut ekranu 2020-12-26 o 16 01 56](https://user-images.githubusercontent.com/10917792/103153938-b0179700-4794-11eb-8f1c-122740a43d4e.png)
![Zrzut ekranu 2020-12-26 o 16 02 16](https://user-images.githubusercontent.com/10917792/103153941-b148c400-4794-11eb-924b-cd5993f5d461.png)
![Zrzut ekranu 2020-12-26 o 16 02 24](https://user-images.githubusercontent.com/10917792/103153943-b279f100-4794-11eb-8fa0-b2a9401591a3.png)
![Zrzut ekranu 2020-12-26 o 16 02 43](https://user-images.githubusercontent.com/10917792/103153945-b443b480-4794-11eb-9a07-31090f1fc45b.png)
![Zrzut ekranu 2020-12-26 o 16 02 57](https://user-images.githubusercontent.com/10917792/103153948-b60d7800-4794-11eb-9bce-7187f9078433.png)
![Zrzut ekranu 2020-12-26 o 16 03 04](https://user-images.githubusercontent.com/10917792/103153949-b7d73b80-4794-11eb-8ebf-ad53488626e1.png)
![Zrzut ekranu 2020-12-26 o 16 03 15](https://user-images.githubusercontent.com/10917792/103153951-b86fd200-4794-11eb-87fb-73632d78b0c9.png)
![Zrzut ekranu 2020-12-26 o 16 03 35](https://user-images.githubusercontent.com/10917792/103153952-bad22c00-4794-11eb-80bd-3f516733d66c.png)
![Zrzut ekranu 2020-12-26 o 16 03 43](https://user-images.githubusercontent.com/10917792/103153953-bb6ac280-4794-11eb-9f77-b3f8eb8f7ac1.png)
![Zrzut ekranu 2020-12-26 o 16 03 52](https://user-images.githubusercontent.com/10917792/103153955-bc9bef80-4794-11eb-9ac2-630c8a9dc2b6.png)
![Zrzut ekranu 2020-12-26 o 16 04 04](https://user-images.githubusercontent.com/10917792/103153956-bdcd1c80-4794-11eb-9632-ed69fefd117d.png)

**Comment by michaelKurowski** [comment]
Seems fine on Mac.
So the only thing is to fix header on iOS on some pages.

**Comment by MarcinGrzeszczak** [comment]
MacBook Air 13 early 2015
macOS Big Sur 11.0.1
Safari 14.0.1
Resolution: 1440x900
Native Display without Retina
![Zrzut ekranu 2020-12-26 o 16 15 30](https://user-images.githubusercontent.com/10917792/103154176-236dd880-4796-11eb-8a75-c799d733b115.png)
![Zrzut ekranu 2020-12-26 o 16 15 48](https://user-images.githubusercontent.com/10917792/103154215-3da7b680-4796-11eb-92ef-9ec30dcbd81e.png)
![Zrzut ekranu 2020-12-26 o 16 15 57](https://user-images.githubusercontent.com/10917792/103154178-27015f80-4796-11eb-87e1-ba9fb7ea4f57.png)
![Zrzut ekranu 2020-12-26 o 16 16 10](https://user-images.githubusercontent.com/10917792/103154179-2799f600-4796-11eb-952b-7494876d416b.png)
![Zrzut ekranu 2020-12-26 o 16 16 19](https://user-images.githubusercontent.com/10917792/103154180-28cb2300-4796-11eb-9dd6-8d1025b88ac1.png)
![Zrzut ekranu 2020-12-26 o 16 17 12](https://user-images.githubusercontent.com/10917792/103154183-29fc5000-4796-11eb-87f0-06d59c51a933.png)
![Zrzut ekranu 2020-12-26 o 16 17 22](https://user-images.githubusercontent.com/10917792/103154184-2a94e680-4796-11eb-9a7d-8b05c5bc70f9.png)
![Zrzut ekranu 2020-12-26 o 16 17 33](https://user-images.githubusercontent.com/10917792/103154188-2bc61380-4796-11eb-99db-13a1ed5a906b.png)
![Zrzut ekranu 2020-12-26 o 16 17 39](https://user-images.githubusercontent.com/10917792/103154193-2c5eaa00-4796-11eb-9d5d-3fbaffae5225.png)
![Zrzut ekranu 2020-12-26 o 16 17 56](https://user-images.githubusercontent.com/10917792/103154198-2cf74080-4796-11eb-8862-e1116d5f745e.png)
![Zrzut ekranu 2020-12-26 o 16 18 14](https://user-images.githubusercontent.com/10917792/103154200-2d8fd700-4796-11eb-8b86-73ad36a6c47c.png)
![Zrzut ekranu 2020-12-26 o 16 18 23](https://user-images.githubusercontent.com/10917792/103154204-2e286d80-4796-11eb-997c-8700d425e239.png)
![Zrzut ekranu 2020-12-26 o 16 18 29](https://user-images.githubusercontent.com/10917792/103154206-2ec10400-4796-11eb-90a4-616dfb142907.png)
![Zrzut ekranu 2020-12-26 o 16 18 37](https://user-images.githubusercontent.com/10917792/103154207-2f599a80-4796-11eb-8abd-3c099ad40f6d.png)

**Comment by michaelKurowski** [comment]
Actually it's an issue on all browsers, not Safari only.

**Comment by MarcinGrzeszczak** [comment]
> I see only one problem - some pages are wider than the header. Let me know if I don't notice sth

Also empty space between lines is too big (IOS) especially on article page

**Comment by michaelKurowski** [comment]
I think it's universal, independent of browser @MarcinGrzeszczak 
https://github.com/Jordan141/articleblog/issues/81
Please throw UX issues into this ticket, we have it assigned to u, since we might be a bit skewed as we work on the blog every day.

**Comment by michaelKurowski** [comment]
Since Safari has no specific bugs, I'm closing the ticket
