### ISSUE TITLE
Create Authors route

### ISSUE THREAD

**Issue by Jordan141** [Jordan141/articleblog#84]
We need a new backend route to get all users who are of user.type author.

- Create GET route to render EJS Authors template on /authors
- Have the GET route access and deliver authors to the EJS template before serving.
- Only deliver data for this page, ie. don't be delivering whole user object when only the name, picture and desc are used.

**Comment by michaelKurowski** [comment]
Closed: https://github.com/Jordan141/articleblog/pull/83
